### ISSUE TITLE
Set up Mobile Framework

### ISSUE THREAD

**Issue by zawadzkip** [msoeSE/TheHopefuls#5]
Pull Request https://github.com/msoeSE/TheHopefuls/pull/6

**Comment by sorianog** [comment]
Verified that the builds are setup on Bitrise and that builds are running successfully for the mobile branches (master, mobile-master, mobile-dev)

**Comment by sorianog** [comment]
Pat says app was able to run on iOS (he is the only with a Mac). I was able to verify that the app runs on Android (through an emulator).
